-- Add AWAITING_PAYMENT to contract state CHECK constraint

ALTER TABLE T_contract DROP CONSTRAINT CHK_contract_state;
ALTER TABLE T_contract ADD CONSTRAINT CHK_contract_state CHECK (state IN ('DRAFT', 'OFFERED', 'ACCEPTED', 'AWAITING_APPROVAL', 'APPROVED', 'AWAITING_PAYMENT', 'RUNNING', 'CANCELLED', 'EXPIRED', 'TERMINATED'));
